### ISSUE TITLE
Update recipes endpoint

### ISSUE THREAD

**Issue by udeyrishi** [SmartFoodTracker/SmartFoodTrackerAndroid#10]
The `/recipes?<query>` endpoint has been replaced by `:userid/recipes?<query>`. This means that the default `:userId/recipes` (without any query) will return the recipes for the home screen, while the version with the query can be used for searching.

**Comment by udeyrishi** [comment]
Addressed by e69182c

**Comment by ahoskins** [comment]
This will not work as of now. The :userId/recipes endpoint overrides the ?ingredients with the user's current ingredients. I can change this on the server.

**Comment by udeyrishi** [comment]
@ahoskins Yeah I think that'd be nice. So IIUC, after the proposed change, if I don't provide the `?ingredients` query, it'll default to the user's inventory. But if I do provide, it'll use that, and ignore the user's inventory. Correct?

**Comment by ahoskins** [comment]
Yes. The explicitly given `ingredients` in query will have highest precedence.
