### ISSUE TITLE
Update the create item flow to match the new API semantics

### ISSUE THREAD

**Issue by udeyrishi** [SmartFoodTracker/SmartFoodTrackerAndroid#4]
The PUT /:deviceId/inventory endpoint now does a string comparison on the title, and if an item already exists with that title (say with ID itemId), reroutes the request to PUT :/deviceId/inventory/:itemId. For the app, this should mean that before firing the create item request, do a GET on the inventory and see if an item with that title exists, and show an action message "Item foo already exists, do you want to update that instead? [Y/N]".

@ahoskins Should we do this, or just show an error and drop everything?

**Comment by ahoskins** [comment]
I would throw a toast that says "item already exists", and cancel the operation.

**Comment by udeyrishi** [comment]
@ahoskins Still need to implement this

**Comment by udeyrishi** [comment]
Fixed by 66eb74a2
