### ISSUE TITLE
[View] Scrolling momentum bubble doesn't extended across layout

### ISSUE THREAD

**Issue by kohsh** [SmartFoodTracker/SmartFoodTrackerAndroid#7]
![screenshot_20170307-095032](https://cloud.githubusercontent.com/assets/5834110/23667717/0a40d5e6-031c-11e7-8ba8-1e5fa714bd07.png)

The bubble I'm talking about is seen above "sammie" in this screen shot. Does that make sense?

**Comment by udeyrishi** [comment]
@kyleoshaughnessy I don't think we can fix this. I think this is the standard Android behaviour. The width of the shadows == width of the actual list item. The only way to make it full width would be to make the item full width as well without any margin. And I don't think that'll look nice. Reopen the issue if you have any other suggestions.
